---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:12.14.1

    steps:
    # check out source code to working directory
      - checkout 
      - run:
          name: Code Check out
          command: |
            echo “Hello!”
            
  build_deploy:
    docker:
      - image: circleci/node:13.6.0
    
    steps:
    # check out source code to working directory
      - checkout 
      - run:
          name: Build 
          command: |
           cd Cloud && npm install
  

workflows:
  version: 2
  pr-check-workflow:
    jobs:
      - pr_check
  build-deploy-workflow:
    jobs:
      - build_deploy
